### ISSUE TITLE
Add a record of a relationship

### ISSUE THREAD

**Issue by burotica49** [izica/relations-widgets-for-backpack#5]
Hello,

Is it to create a record button inline or when adding a record of a relationship, whether the foreign key is passed.

I have created a Controler Client with a relation_table / hasMany for a list of contacts of this client.

When you click on Add for the contact list, you must re-select the customer. Is it possible to pass the customer ID, so that it is already selected when adding, or even better in inline_create? 

Best regard

**Comment by izica** [comment]
Hi, check 3.0
https://github.com/izica/relations-widgets-for-backpack#30-whats-new
and next check this
https://github.com/izica/relations-widgets-for-backpack#how-to-enable-creating-related-model

**Comment by izica** [comment]
@burotica49 
Hi, check 3.0
https://github.com/izica/relations-widgets-for-backpack#30-whats-new
and next check this
https://github.com/izica/relations-widgets-for-backpack#how-to-enable-creating-related-model
