### ISSUE TITLE
Many result

### ISSUE THREAD

**Issue by ades4827** [izica/relations-widgets-for-backpack#6]
Hi, 
you have already considered integrating datatable into the relation_table version?
if there are many results the page becomes very long and inserting the plugin in the view is not enough. it should be integrated on the server side.

Thanks for this great plugin

**Comment by izica** [comment]
@ades4827 
Hi, in 3.0 table pagination added
check 'per_page' attribute

**Comment by ades4827** [comment]
this news is fantastic! it's early christmas ;) @izica
