### ISSUE TITLE
relation_table pagination and documentation

### ISSUE THREAD

**Issue by fronbow** [izica/relations-widgets-for-backpack#8]
Hi,
In the documentation, it says that the relation_table has pagination but there isn't any functionality in the source. That functionality appears to be in the relation_panel source.
Also for relation_table, you have to implicitly set 
`'button_create' => false,`
so that the Add button doesn't show up, even though I set
`'buttons' => false,`
in the same block.

Also in the documentation for relation_table, you've written `fields` where it should be `columns`.

**Comment by izica** [comment]
@fronbow Hello, for pagination check `per_page` property in 3.0 version. 
Thank you about `fields` mistake, i'll fix it.

**Comment by izica** [comment]
@fronbow Ah, now I get it, I changed panel instead of table by mistake, ty so much for help

**Comment by izica** [comment]
released 3.1
